repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          [
            "--max-line-length=88",
            "--per-file-ignores=__init__.py:F401,F403",
            "--extend-ignore=E203,F722"
          ]
